### PR TITLE
Fix memory leak SPIKE solvers

### LINKED ISSUE #319: [BUG] Memory leak in SPIKE solvers
### Version

dev

### Describe the bug

Memory leak in SPIKE solvers.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TLCFEM**

### CODE REVIEW

File: Toolbox/feast-src/spike-src/Xspike_smp.f90 [hunk 1]
```diff
@@ -1477,6 +1471,12 @@ subroutine T_DEC(spike_gbtrs2) &
   redsys_end_time = 0.0d0
 else
```
Comment (TLCFEM) [inline Toolbox/feast-src/spike-src/Xspike_smp.f90:1472]: The two arrays are only deallocated in this branch.
